/* eslint-disable @typescript-eslint/no-explicit-any */

import { GenerateConsoleUrlRoute as OriginalGenerateConsoleUrlRoute } from './api/aws/console/POST';
import { AssumeRoleRoute as OriginalAssumeRoleRoute } from './api/aws/assume-role/POST';
import { FederateRoute as OriginalFederateRoute } from './api/aws/federate/GET';
import { ListAssumablesRoute as OriginalListAssumablesRoute } from './api/user/assumables/GET';
import { SearchAccountsRoute as OriginalSearchAccountsRoute } from './api/user/assumables/search/GET';
import { GetCurrentUserRoute as OriginalGetCurrentUserRoute } from './api/user/me/GET';
import { FavoriteAccountRoute as OriginalFavoriteAccountRoute } from './api/user/favorites/POST';
import { UnfavoriteAccountRoute as OriginalUnfavoriteAccountRoute } from './api/user/favorites/DELETE';
import { StoreCredentialRoute as OriginalStoreCredentialRoute } from './api/admin/credentials/POST';
import { GrantAccessRoute as OriginalGrantAccessRoute } from './api/admin/access/POST';
import { RevokeAccessRoute as OriginalRevokeAccessRoute } from './api/admin/access/DELETE';
import { SetAccountNicknameRoute as OriginalSetAccountNicknameRoute } from './api/admin/account/nickname/PUT';
import { RemoveAccountNicknameRoute as OriginalRemoveAccountNicknameRoute } from './api/admin/account/nickname/DELETE';
import { StoreCredentialRelationshipRoute as OriginalStoreCredentialRelationshipRoute } from './api/admin/credentials/relationship/POST';
import { RemoveCredentialRelationshipRoute as OriginalRemoveCredentialRelationshipRoute } from './api/admin/credentials/relationship/DELETE';
import { HideRoleRoute as OriginalHideRoleRoute } from './api/user/assumable/hidden/POST';
import { UnhideRoleRoute as OriginalUnhideRoleRoute } from './api/user/assumable/hidden/DELETE';
import { SetRoleConfigRoute as OriginalSetRoleConfigRoute } from './api/admin/role/config/PUT';
import { DeleteRoleConfigRoute as OriginalDeleteRoleConfigRoute } from './api/admin/role/config/DELETE';
import { FederateWrapperRoute as OriginalFederateWrapperRoute } from './federate/GET';
import { CreateTokenRoute as OriginalCreateTokenRoute } from './api/user/token/POST';
import { DeleteTokenRoute as OriginalDeleteTokenRoute } from './api/user/token/DELETE';
import { ListTokensRoute as OriginalListTokensRoute } from './api/user/tokens/GET';
import { ValidateCredentialsRoute as OriginalValidateCredentialsRoute } from './api/admin/credentials/validate/POST';
import { TestCredentialChainRoute as OriginalTestCredentialChainRoute } from './api/admin/credentials/test-chain/POST';
import { ListAccountRolesRoute as OriginalListAccountRolesRoute } from './api/admin/account/roles/POST';
import { ListAuditLogsRoute as OriginalListAuditLogsRoute } from './api/admin/audit-logs/GET';
import { GetCostSummaryRoute as OriginalGetCostSummaryRoute } from './api/cost/summary/GET';
import { GetAccountCostRoute as OriginalGetAccountCostRoute } from './api/cost/account/GET';
import { GetCostTrendsRoute as OriginalGetCostTrendsRoute } from './api/cost/trends/GET';
import { CreateSpendAlertRoute as OriginalCreateSpendAlertRoute } from './api/admin/cost/alerts/POST';
import { DeleteSpendAlertRoute as OriginalDeleteSpendAlertRoute } from './api/admin/cost/alerts/DELETE';
import { EnableDataCollectionRoute as OriginalEnableDataCollectionRoute } from './api/admin/collection/config/POST';
import { DisableDataCollectionRoute as OriginalDisableDataCollectionRoute } from './api/admin/collection/config/DELETE';

export const GenerateConsoleUrlRoute: any = OriginalGenerateConsoleUrlRoute;
export const AssumeRoleRoute: any = OriginalAssumeRoleRoute;
export const FederateRoute: any = OriginalFederateRoute;
export const ListAssumablesRoute: any = OriginalListAssumablesRoute;
export const SearchAccountsRoute: any = OriginalSearchAccountsRoute;
export const GetCurrentUserRoute: any = OriginalGetCurrentUserRoute;
export const FavoriteAccountRoute: any = OriginalFavoriteAccountRoute;
export const UnfavoriteAccountRoute: any = OriginalUnfavoriteAccountRoute;
export const StoreCredentialRoute: any = OriginalStoreCredentialRoute;
export const GrantAccessRoute: any = OriginalGrantAccessRoute;
export const RevokeAccessRoute: any = OriginalRevokeAccessRoute;
export const SetAccountNicknameRoute: any = OriginalSetAccountNicknameRoute;
export const RemoveAccountNicknameRoute: any = OriginalRemoveAccountNicknameRoute;
export const StoreCredentialRelationshipRoute: any = OriginalStoreCredentialRelationshipRoute;
export const RemoveCredentialRelationshipRoute: any = OriginalRemoveCredentialRelationshipRoute;
export const HideRoleRoute: any = OriginalHideRoleRoute;
export const UnhideRoleRoute: any = OriginalUnhideRoleRoute;
export const SetRoleConfigRoute: any = OriginalSetRoleConfigRoute;
export const DeleteRoleConfigRoute: any = OriginalDeleteRoleConfigRoute;
export const FederateWrapperRoute: any = OriginalFederateWrapperRoute;
export const CreateTokenRoute: any = OriginalCreateTokenRoute;
export const DeleteTokenRoute: any = OriginalDeleteTokenRoute;
export const ListTokensRoute: any = OriginalListTokensRoute;
export const ValidateCredentialsRoute: any = OriginalValidateCredentialsRoute;
export const TestCredentialChainRoute: any = OriginalTestCredentialChainRoute;
export const ListAccountRolesRoute: any = OriginalListAccountRolesRoute;
export const ListAuditLogsRoute: any = OriginalListAuditLogsRoute;
export const GetCostSummaryRoute: any = OriginalGetCostSummaryRoute;
export const GetAccountCostRoute: any = OriginalGetAccountCostRoute;
export const GetCostTrendsRoute: any = OriginalGetCostTrendsRoute;
export const CreateSpendAlertRoute: any = OriginalCreateSpendAlertRoute;
export const DeleteSpendAlertRoute: any = OriginalDeleteSpendAlertRoute;
export const EnableDataCollectionRoute: any = OriginalEnableDataCollectionRoute;
export const DisableDataCollectionRoute: any = OriginalDisableDataCollectionRoute;
