import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import path from 'path';
import { readFileSync, writeFileSync } from 'fs';

export default defineConfig({
  root: 'app',
  plugins: [
    react(),
    tailwindcss(),
    {
      name: 'spa-shell-embed',
      closeBundle() {
        const html: string = readFileSync(path.resolve(__dirname, 'app/dist/index.html'), 'utf-8');
        const output: string = `// Auto-generated by Vite build plugin — DO NOT EDIT.\nexport const SPA_HTML: string = ${JSON.stringify(html)};\n`;
        writeFileSync(path.resolve(__dirname, 'src/generated/spa-shell.ts'), output);
      },
    },
  ],
  resolve: {
    alias: {
      '@/components': path.resolve(__dirname, 'components'),
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    minify: 'terser',
    terserOptions: {
      compress: {
        drop_console: true,
        drop_debugger: true,
      },
    },
  },
});
