export const CREDENTIAL_EXPIRY_BUFFER_MINUTES: number = 5;
export const NUMBER_OF_CREDENTIALS_TO_REFRESH: number = 10;
export const CREDENTIAL_REFRESH_INTERVAL_MINUTES: number = 45;
export const INTERNAL_REQUEST_VALID_TIME_WINDOW_MILLISECONDS: number = 1 * 1000;
