# $version: v3-1779804803
name: Upstream Sync

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  sync:
    if: ${{ github.event.repository.fork }}
    name: Sync From Upstream
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Sync Upstream Changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: Rexezuge-CloudflareWorkers/AWS-AccessBridge
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
